module.exports = {
    ETHEREUM_RPC_URL: process.env.ETHEREUM_RPC_URL,
    MICROLOAN_CONTRACT_ADDRESS: process.env.MICROLOAN_CONTRACT_ADDRESS,
    ADMIN_WALLET_ADDRESS: process.env.ADMIN_WALLET_ADDRESS,
    ADMIN_PRIVATE_KEY: process.env.ADMIN_PRIVATE_KEY
}